_enabled_editors:
  - content
  - data
  - visual
_inputs:
  xs:
    type: auto
    cascade: true
_select_data:
  sxs: []
_structures:
  sx:
    style: select
    id_key:
    values:
_editables:
  block:
    allow_custom_markup: false
    remove_custom_markup: false
    blockquote:
    bold:
    bulletedlist:
    center:
    code: true
    copyformatting: true
    correct_orientation: true
    embed: true
    expandable: true
    format:
    height:
    horizontalrule:
    image:
    image_size_attributes: true
    indent:
    italic:
    justify:
    left:
    link: true
    mime_type: image/webp
    numberedlist:
    outdent:
    paths:
    redo:
    removeformat:
    resize_style: contain
    right:
    snippet:
    strike:
    styles:
    subscript: true
    superscript: true
    table: true
    underline: true
    undo: true
    width:
editor:
  default_path: /.nojekyll
source_editor:
  tab_size: 2
  theme: github
  show_gutter: true
timezone: Etc/UTC
